# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dc4bbc2f999e37cd9106dd5329a1d480f4e3f10c840f1e9db53340e7b65db3b940383ccfe0e27997afdc1ba5cb97b51d8900c0fce4213ab547a240bad06b205a

test:
  secret_key_base: 64c100b7d4140f341b15ef540583732cfa5f15edd879d730fa0031fab9c3654819b2ab765a8ead578eb551523b049a6b4e0094020a1360ac50497991a95f0262

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
